# Generated by Django 3.2.7 on 2022-01-15 11:19

import ast
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=ast.Delete, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
