# Generated by Django 3.2.7 on 2022-01-15 11:36

import ast
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('discription', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=ast.Delete, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='lists.Item')),
                ('shared_with', models.ManyToManyField(related_name='shared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
